### ISSUE TITLE
Фон navigation bar'а

### ISSUE THREAD

**Issue by vitosotdihaet** [lavaFrai/mai3#4]
# Проблема
Фон navigation bar'а андроида белый вне зависимости от темы приложения

<img src=https://github.com/lavaFrai/mai3/assets/67521698/a59bc8f7-7e27-44e8-bd2f-ca4161d7f546, height=500px>
<img src=https://github.com/lavaFrai/mai3/assets/67521698/fe5003ab-e06f-498b-928d-fb4967aba218, height=500px>

Хотелось бы видеть цвет фона такой же, как и цвет navigation bar'а приложения (#f4eae9 и #2c1f1e)

# Как повторить
Телефон: Sony Xperia 5 IV, Anroid 14
Build: release@0.5.0b

**Comment by lavafrai** [comment]
Решено буквально в последнем коммите, скоро будет опубликован билд для всех.
Если очень напрягает, приложу нерелизную сборку сюда:
https://drive.google.com/file/d/1uZ5a3AQmOIXBwhFKqLTlkkcGQePwDLxe/view?usp=drivesdk
Если все работает, закроем issue
